/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.10
 * Generated at: 2024-05-23 09:03:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("@import url('https://fonts.googleapis.com/css?family=Raleway:400,700');\r\n");
      out.write(".container{\r\n");
      out.write("margin-top:100px;\r\n");
      out.write("}\r\n");
      out.write("* {\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;	\r\n");
      out.write("	font-family: Raleway, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	background: linear-gradient(90deg, #C7C5F4, #776BCC);		\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	min-height: 100vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".screen {		\r\n");
      out.write("	background: linear-gradient(260deg, #5D54A4, #7C78B8);		\r\n");
      out.write("	position: relative;	\r\n");
      out.write("	height: 600px;\r\n");
      out.write("	width: 360px;	\r\n");
      out.write("	box-shadow: 0px 0px 24px #5C5696;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".screen__content {\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("	position: relative;	\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".screen__background {		\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	right: 0;\r\n");
      out.write("	bottom: 0;\r\n");
      out.write("	z-index: 0;\r\n");
      out.write("	-webkit-clip-path: inset(0 0 0 0);\r\n");
      out.write("	clip-path: inset(0 0 0 0);	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".screen__background__shape {\r\n");
      out.write("	transform: rotate(45deg);\r\n");
      out.write("	position: absolute;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".screen__background__shape1 {\r\n");
      out.write("	height: 520px;\r\n");
      out.write("	width: 520px;\r\n");
      out.write("	background: #FFF;	\r\n");
      out.write("	top: -50px;\r\n");
      out.write("	right: 120px;	\r\n");
      out.write("	border-radius: 0 72px 0 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".screen__background__shape2 {\r\n");
      out.write("	height: 220px;\r\n");
      out.write("	width: 220px;\r\n");
      out.write("	background: #6C63AC;	\r\n");
      out.write("	top: -172px;\r\n");
      out.write("	right: 0;	\r\n");
      out.write("	border-radius: 32px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".screen__background__shape3 {\r\n");
      out.write("	height: 540px;\r\n");
      out.write("	width: 190px;\r\n");
      out.write("	background: linear-gradient(270deg, #5D54A4, #6A679E);\r\n");
      out.write("	top: -24px;\r\n");
      out.write("	right: 0;	\r\n");
      out.write("	border-radius: 32px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".screen__background__shape4 {\r\n");
      out.write("	height: 400px;\r\n");
      out.write("	width: 200px;\r\n");
      out.write("	background: #7E7BB9;	\r\n");
      out.write("	top: 420px;\r\n");
      out.write("	right: 50px;	\r\n");
      out.write("	border-radius: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login {\r\n");
      out.write("	width: 320px;\r\n");
      out.write("	padding: 30px;\r\n");
      out.write("	padding-top: 156px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login__field {\r\n");
      out.write("	padding: 20px 0px;	\r\n");
      out.write("	position: relative;	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login__icon {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 30px;\r\n");
      out.write("	color: #7875B5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login__input {\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-bottom: 2px solid #D1D1D4;\r\n");
      out.write("	background: none;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	padding-left: 24px;\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	width: 75%;\r\n");
      out.write("	transition: .2s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login__input:active,\r\n");
      out.write(".login__input:focus,\r\n");
      out.write(".login__input:hover {\r\n");
      out.write("	outline: none;\r\n");
      out.write("	border-bottom-color: #6A679E;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login__submit {\r\n");
      out.write("	background: #fff;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	margin-top: 30px;\r\n");
      out.write("	padding: 16px 20px;\r\n");
      out.write("	border-radius: 26px;\r\n");
      out.write("	border: 1px solid #D4D3E8;\r\n");
      out.write("	text-transform: uppercase;\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	color: #4C489D;\r\n");
      out.write("	box-shadow: 0px 2px 2px #5C5696;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	transition: .2s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login__submit:active,\r\n");
      out.write(".login__submit:focus,\r\n");
      out.write(".login__submit:hover {\r\n");
      out.write("	border-color: #6A679E;\r\n");
      out.write("	outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button__icon {\r\n");
      out.write("	font-size: 24px;\r\n");
      out.write("	margin-left: auto;\r\n");
      out.write("	color: #7875B5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-login {	\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	height: 140px;\r\n");
      out.write("	width: 160px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	bottom: 0px;\r\n");
      out.write("	right: 0px;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-icons {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-login__icon {\r\n");
      out.write("	padding: 20px 10px;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	text-decoration: none;	\r\n");
      out.write("	text-shadow: 0px 0px 8px #7875B5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-login__icon:hover {\r\n");
      out.write("	transform: scale(1.5);	\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("	<div class=\"screen\">\r\n");
      out.write("		<div class=\"screen__content\">\r\n");
      out.write("			<form class=\"login\">\r\n");
      out.write("				<div class=\"login__field\">\r\n");
      out.write("					<i class=\"login__icon fa fa-user\"></i>\r\n");
      out.write("					<input type=\"text\" class=\"login__input\" placeholder=\"Username / Email\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"login__field\">\r\n");
      out.write("					<i class=\"login__icon fa fa-lock\"></i>\r\n");
      out.write("					<input type=\"password\" class=\"login__input\" placeholder=\"Password\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<button class=\"button login__submit\">\r\n");
      out.write("					<span class=\"button__text\">Log In Now</span>\r\n");
      out.write("					<i class=\"button__icon fas fa-chevron-right\"></i>\r\n");
      out.write("				</button>				\r\n");
      out.write("			</form>\r\n");
      out.write("			<div class=\"social-login\">\r\n");
      out.write("				<h3>log in via</h3>\r\n");
      out.write("				<div class=\"social-icons\">\r\n");
      out.write("					<a href=\"#\" class=\"social-login__icon fa-fa-instagram\"></a>\r\n");
      out.write("					<a href=\"#\" class=\"social-login__icon fa-fa-facebook\"></a>\r\n");
      out.write("					<a href=\"#\" class=\"social-login__icon fa-fa-twitter\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"screen__background\">\r\n");
      out.write("			<span class=\"screen__background__shape screen__background__shape4\"></span>\r\n");
      out.write("			<span class=\"screen__background__shape screen__background__shape3\"></span>		\r\n");
      out.write("			<span class=\"screen__background__shape screen__background__shape2\"></span>\r\n");
      out.write("			<span class=\"screen__background__shape screen__background__shape1\"></span>\r\n");
      out.write("		</div>		\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
