// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddMovieTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addMovie() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.linkText("View Movie")).click();
    driver.findElement(By.linkText("Add +")).click();
    driver.findElement(By.name("mname")).click();
    driver.findElement(By.name("mname")).sendKeys("Bahubali 2");
    driver.findElement(By.name("type")).click();
    driver.findElement(By.name("type")).sendKeys("Action");
    driver.findElement(By.name("timing")).click();
    driver.findElement(By.name("timing")).sendKeys("4pm-8pm");
    driver.findElement(By.name("sub1")).click();
  }
}
