// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DonatorAddTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void donatorAdd() {
    // Test name: DonatorAdd
    // Step # | name | target | value
    // 1 | open | http://localhost:3000/login | 
    driver.get("http://localhost:3000/login");
    // 2 | setWindowSize | 788x816 | 
    driver.manage().window().setSize(new Dimension(788, 816));
    // 3 | click | id=username | 
    driver.findElement(By.id("username")).click();
    // 4 | type | id=username | gokul
    driver.findElement(By.id("username")).sendKeys("gokul");
    // 5 | click | id=password | 
    driver.findElement(By.id("password")).click();
    // 6 | type | id=password | 123
    driver.findElement(By.id("password")).sendKeys("123");
    // 7 | click | css=.text-white | 
    driver.findElement(By.cssSelector(".text-white")).click();
    // 8 | click | css=.ml-auto > .block > button | 
    driver.findElement(By.cssSelector(".ml-auto > .block > button")).click();
    // 9 | click | name=name | 
    driver.findElement(By.name("name")).click();
    // 10 | type | name=name | gokul
    driver.findElement(By.name("name")).sendKeys("gokul");
    // 11 | click | name=emailid | 
    driver.findElement(By.name("emailid")).click();
    // 12 | type | name=emailid | gokul@gmail.com
    driver.findElement(By.name("emailid")).sendKeys("gokul@gmail.com");
    // 13 | click | name=address | 
    driver.findElement(By.name("address")).click();
    // 14 | type | name=address | madurai
    driver.findElement(By.name("address")).sendKeys("madurai");
    // 15 | click | name=phoneNumber | 
    driver.findElement(By.name("phoneNumber")).click();
    // 16 | type | name=phoneNumber | 1234567890
    driver.findElement(By.name("phoneNumber")).sendKeys("1234567890");
    // 17 | click | name=donation | 
    driver.findElement(By.name("donation")).click();
    // 18 | type | name=donation | Money and Dress
    driver.findElement(By.name("donation")).sendKeys("Money and Dress");
    // 19 | click | css=.btn | 
    driver.findElement(By.cssSelector(".btn")).click();
  }
}
