// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Guru99TestCase1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void guru99TestCase1() {
    driver.get("https://www.guru99.com/");
    driver.findElement(By.cssSelector("#menu-item-3173 .nav-drop-title-wrap")).click();
    driver.findElement(By.cssSelector(".gsc-control-cse")).click();
    driver.findElement(By.linkText("Database Testing")).click();
    driver.findElement(By.cssSelector(".entry-content")).click();
    driver.findElement(By.cssSelector("#menu-item-3173 .nav-drop-title-wrap")).click();
    driver.findElement(By.cssSelector("#menu-item-3173 .kadence-svg-icon")).click();
    driver.findElement(By.linkText("➤ HP Loadrunner")).click();
  }
}
