// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PurchaseTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addPurchase() {
    // Test name: AddPurchase
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:3000/viewPurchase |  | 
    driver.get("http://localhost:3000/viewPurchase");
    // 2 | setWindowSize | 1536x816 |  | 
    driver.manage().window().setSize(new Dimension(1536, 816));
    // 3 | click | linkText=Add Purchase |  | 
    driver.findElement(By.linkText("Add Purchase")).click();
    // 4 | click | name=productName |  | 
    driver.findElement(By.name("productName")).click();
    // 5 | select | name=productName | label=Cricket Ball | 
    {
      WebElement dropdown = driver.findElement(By.name("productName"));
      dropdown.findElement(By.xpath("//option[. = 'Cricket Ball']")).click();
    }
    // 6 | click | name=quantity |  | 
    driver.findElement(By.name("quantity")).click();
    // 7 | type | name=quantity | 2 | 
    driver.findElement(By.name("quantity")).sendKeys("2");
    // 8 | click | name=totalPrice |  | 
    driver.findElement(By.name("totalPrice")).click();
    // 9 | click | css=.p-5 |  | 
    driver.findElement(By.cssSelector(".p-5")).click();
    // 10 | click | name=submit |  | 
    driver.findElement(By.name("submit")).click();
  }
  @Test
  public void deletePurchase() {
    // Test name: DeletePurchase
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:3000/viewPurchase |  | 
    driver.get("http://localhost:3000/viewPurchase");
    // 2 | setWindowSize | 1536x816 |  | 
    driver.manage().window().setSize(new Dimension(1536, 816));
    // 4 | click | name=delete11 |  | 
    driver.findElement(By.name("delete11")).click();
    // 5 | assertConfirmation | Do you want to delete? |  | 
    assertThat(driver.switchTo().alert().getText(), is("Do you want to delete?"));
    // 6 | webdriverChooseOkOnVisibleConfirmation |  |  | 
    driver.switchTo().alert().accept();
  }
  @Test
  public void updatePurchase() {
    // Test name: UpdatePurchase
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:3000/viewPurchase |  | 
    driver.get("http://localhost:3000/viewPurchase");
    // 2 | setWindowSize | 1536x816 |  | 
    driver.manage().window().setSize(new Dimension(1536, 816));
    // 3 | click | id=update15 |  | 
    driver.findElement(By.id("update15")).click();
    // 4 | click | name=quantity |  | 
    driver.findElement(By.name("quantity")).click();
    // 5 | type | name=quantity | 3 | 
    driver.findElement(By.name("quantity")).sendKeys("3");
    // 6 | click | name=totalPrice |  | 
    driver.findElement(By.name("totalPrice")).click();
    // 7 | click | css=.card |  | 
    driver.findElement(By.cssSelector(".card")).click();
    // 8 | click | name=totalPrice |  | 
    driver.findElement(By.name("totalPrice")).click();
    // 9 | click | css=.card |  | 
    driver.findElement(By.cssSelector(".card")).click();
    // 10 | click | name=submit |  | 
    driver.findElement(By.name("submit")).click();
  }
}
