// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddPassengerTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addPassenger() {
    // Test name: AddPassenger
    // Step # | name | target | value
    // 1 | open | http://localhost:3000/1/viewPassengerList | 
    driver.get("http://localhost:3000/1/viewPassengerList");
    // 2 | setWindowSize | 785x510 | 
    driver.manage().window().setSize(new Dimension(785, 510));
    // 3 | click | linkText=Add Passenger | 
    driver.findElement(By.linkText("Add Passenger")).click();
    // 4 | click | name=name | 
    driver.findElement(By.name("name")).click();
    // 5 | type | name=name | karthi
    driver.findElement(By.name("name")).sendKeys("karthi");
    // 6 | click | name=age | 
    driver.findElement(By.name("age")).click();
    // 7 | type | name=age | 26
    driver.findElement(By.name("age")).sendKeys("26");
    // 8 | click | name=classType | 
    driver.findElement(By.name("classType")).click();
    // 9 | select | name=classType | label=AC
    {
      WebElement dropdown = driver.findElement(By.name("classType"));
      dropdown.findElement(By.xpath("//option[. = 'AC']")).click();
    }
    // 10 | click | name=gender | 
    driver.findElement(By.name("gender")).click();
    // 11 | select | name=gender | label=Male
    {
      WebElement dropdown = driver.findElement(By.name("gender"));
      dropdown.findElement(By.xpath("//option[. = 'Male']")).click();
    }
    // 12 | click | name=phone | 
    driver.findElement(By.name("phone")).click();
    // 13 | type | name=phone | 6398745632
    driver.findElement(By.name("phone")).sendKeys("6398745632");
    // 14 | click | css=.btn | 
    driver.findElement(By.cssSelector(".btn")).click();
    // 15 | runScript | window.scrollTo(0,0) | 
    js.executeScript("window.scrollTo(0,0)");
  }
}
